name: Build and Push Docker image to Docker Hub

on: push
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: 518990/gittext:new
  deploy:
    name: Deploy Next.js App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Pull Docker image from Docker Hub
        run: docker pull 518990/gittext:new

      - name: Run Docker container
        run: docker run -d --name nextjs-app -p 3000:3000 518990/gittext:new