name: Deploy Docker image to EC2

on:
  push:
    branches:
      - main  # or whatever branch you want to deploy from

jobs:
  deploy_to_ec2:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into EC2 instance and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@13.232.155.130 << 'EOF'
            docker pull 518990/gittext:new
            docker stop nextjs-app || true
            docker rm nextjs-app || true
            docker run -d --name nextjs-app -p 3000:3000 518990/gittext:new
          EOF