name: Deploy Docker image to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy_to_ec2:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Deploy Docker image
        run: |
          ssh ubuntu@13.232.155.130 -o StrictHostKeyChecking=no -i <(echo "$SSH_PRIVATE_KEY") << 'EOF'
            docker pull 518990/gittext:new
            docker stop nextjs-app || true
            docker rm nextjs-app || true
            docker run -d --name nextjs-app -p 3000:3000 518990/gittext:new
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
